# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: snip

env:
  - SNAP="/snap/snapcraft/15950"
  - SNAP_NAME="snapcraft"
  - SNAP_VERSION="15950"

before:
  hooks:  
    - go mod tidy

builds:
  - id: snip-linux
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  - id: snip-windows
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"


homebrew_casks:
  - name: snip
    binary: snip
    url:
      template: "https://github.com/matheuzgomes/Snip/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://github.com/matheuzgomes/Snip"
    description: "A fast and lightweight note-taking CLI application"
    repository:
      owner: matheuzgomes
      name: Snip
      branch: master
    caveats: |
      Data files are stored in ~/.snip/
      To completely remove all data, run: rm -rf ~/.snip/

winget:
  - name: snip
    publisher: "Notes"
    short_description: "A fast and lightweight note-taking CLI application"
    license: "MIT"
    publisher_url: "https://github.com/matheuzgomes/Snip"
    publisher_support_url: "https://github.com/matheuzgomes/Snip/issues/new"
    package_identifier: "Notes.Snip"
    homepage: "https://github.com/matheuzgomes/Snip"
    description: "Snip is a terminal-based note management application that allows you to create, edit, view, and delete notes quickly and efficiently."
    license_url: "https://github.com/matheuzgomes/Snip/blob/master/LICENSE"
    tags:
      - cli
      - notes
      - productivity
      - terminal
    repository:
      owner: matheuzgomes
      name: Snip
      branch: master

scoops:
  - name: snip
    url_template: "https://github.com/matheuzgomes/Snip/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://github.com/matheuzgomes/Snip"
    description: "A fast and lightweight note-taking CLI application"
    license: "MIT"
    persist:
      - ".snip"
    repository:
      owner: matheuzgomes
      name: Snip
      branch: master


release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
