version: 2

project_name: snip

before:
  hooks:  
    - go mod tidy

builds:
  - id: snip-windows
    env:
      - CGO_ENABLED=1
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - formats: [zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'snip_{{ .Version }}_checksums_windows.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

scoops:
  - name: snip
    url_template: "https://github.com/matheuzgomes/Snip/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://github.com/matheuzgomes/Snip"
    description: "A fast and lightweight note-taking CLI application"
    license: "MIT"
    persist:
      - ".snip"
    repository:
      owner: matheuzgomes
      name: Snip
      branch: master

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
