# This file was generated by GoReleaser. DO NOT EDIT.
cask "snip" do
  name "snip"
  desc "A fast and lightweight note-taking CLI application"
  homepage "https://github.com/matheuzgomes/Snip"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "snip"

  on_linux do
    on_intel do
      url "https://github.com/matheuzgomes/Snip/releases/download/v#{version}/snip_Linux_x86_64.tar.gz"
      sha256 "0d09f1a2f39faa2b17ad9876f03eedb7b9f96f74b977e058b8074996da04e73d"
    end
    on_arm do
      url "https://github.com/matheuzgomes/Snip/releases/download/v#{version}/snip_Linux_arm64.tar.gz"
      sha256 "dddb3c9ba24e42de2b2169ad631e04ca29369a0b5b791a202f45ff2d061969df"
    end
  end

  caveats do
    "Data files are stored in ~/.snip/"
    "To completely remove all data, run: rm -rf ~/.snip/"
  end

  # No zap stanza required
end
