# This file was generated by GoReleaser. DO NOT EDIT.
cask "snip" do
  name "snip"
  desc "A fast and lightweight note-taking CLI application"
  homepage "https://github.com/matheuzgomes/Snip"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "snip"

  on_linux do
    on_intel do
      url "https://github.com/matheuzgomes/Snip/releases/download/v#{version}/snip_Linux_x86_64.tar.gz"
      sha256 "a1f067310206a063e342295416e64f8c42106b258771bcf917c1bcae2cb18b5a"
    end
    on_arm do
      url "https://github.com/matheuzgomes/Snip/releases/download/v#{version}/snip_Linux_arm64.tar.gz"
      sha256 "dea982593d91118025b5c2beec62f90bd58ae3075d7a671f0c79ecba55d7af5b"
    end
  end

  caveats do
    "Data files are stored in ~/.snip/"
    "To completely remove all data, run: rm -rf ~/.snip/"
  end

  # No zap stanza required
end
