# This file was generated by GoReleaser. DO NOT EDIT.
cask "snip" do
  name "snip"
  desc "A fast and lightweight note-taking CLI application"
  homepage "https://github.com/matheuzgomes/Snip"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "snip"

  on_linux do
    on_intel do
      url "https://github.com/matheuzgomes/Snip/releases/download/v#{version}/snip_Linux_x86_64.tar.gz"
      sha256 "dd7639252f3d541c922ebe23493984afad2dec3a145e20e93f796fafb868afd1"
    end
    on_arm do
      url "https://github.com/matheuzgomes/Snip/releases/download/v#{version}/snip_Linux_arm64.tar.gz"
      sha256 "03ba4af8fe16fd03c0a957b08f725044419287dfb9fda9dbfa0b96c66325322c"
    end
  end

  caveats do
    "Data files are stored in ~/.snip/"
    "To completely remove all data, run: rm -rf ~/.snip/"
  end

  # No zap stanza required
end
